"""Static, pre-authored assessment question-bank content -- NO LLM, no
runtime generation. Consumed by generate_assessment_catalog.py.

Structure, per skill:
    SKILLS = {
        "<skill name, must match skills.name exactly>": {
            "category_description": "<optional, used only in assessment.description>",
            "Beginner": {"duration_minutes": ..., "select_count": ..., "passing_percentage": ..., "questions": [...]},
            "Intermediate": {...},
            "Advanced": {...},
        },
        ...
    }

Each question: (question_text, [option_a, option_b, option_c, option_d], correct_index, explanation)
-- exactly one correct option (MCQ), matching the existing schema's
scoring rule (exact-set-match against assessment_question_answers.correct_option_ids).

To add a new skill: add a new top-level entry with the exact skills.name
value from the catalog and the same three-difficulty structure. The
generator looks up skill_id by name -- no UUIDs are hardcoded here.
"""

PYTHON_BEGINNER = [
    ("Which keyword is used to define a function in Python?",
     ["def", "func", "function", "lambda"], 0,
     "Python functions are defined with the `def` keyword, e.g. `def greet():`."),
    ("What is the output of `print(type([]))`?",
     ["<class 'list'>", "<class 'array'>", "<class 'tuple'>", "<class 'set'>"], 0,
     "Square brackets `[]` create a list literal, so its type is `list`."),
    ("Which of the following creates an empty dictionary?",
     ["{}", "[]", "()", "set()"], 0,
     "Curly braces with nothing inside create an empty dict; `set()` creates an empty set, not a dict."),
    ("What does the `len()` function return for a string?",
     ["The number of words", "The number of characters", "The memory size in bytes", "The ASCII sum of all characters"], 1,
     "`len()` on a string returns the count of characters (code points) in it."),
    ("Which operator performs floor division in Python?",
     ["/", "//", "%", "**"], 1,
     "`//` divides and rounds down to the nearest integer; `/` performs true (float) division."),
    ("What is the correct way to start a single-line comment in Python?",
     ["//", "#", "--", "/* */"], 1,
     "Python uses `#` for single-line comments."),
    ("Which of these is a mutable data type in Python?",
     ["tuple", "str", "list", "int"], 2,
     "Lists can be modified in place (append, remove, etc.); tuples, strings, and ints are immutable."),
    ("What does `list(range(5))` produce?",
     ["[1, 2, 3, 4, 5]", "[0, 1, 2, 3, 4]", "[0, 1, 2, 3, 4, 5]", "[1, 2, 3, 4]"], 1,
     "`range(5)` produces 0 through 4 (5 values), stopping before the given endpoint."),
]

PYTHON_INTERMEDIATE = [
    ("What is a Python decorator primarily used for?",
     ["Styling console output", "Modifying or extending a function's behavior without changing its source code",
      "Defining a class", "Handling exceptions exclusively"], 1,
     "A decorator wraps a function to add behavior (logging, caching, auth checks, etc.) transparently."),
    ("What does `*args` allow a function to accept?",
     ["A fixed number of keyword arguments", "A variable number of positional arguments",
      "Only exactly one argument", "A dictionary of arguments"], 1,
     "`*args` collects any number of extra positional arguments into a tuple."),
    ("Which statement about Python's Global Interpreter Lock (GIL) is true?",
     ["It allows true parallel execution of Python bytecode across threads",
      "It prevents multiple native threads from executing Python bytecode at the same instant",
      "It only exists in Python 2", "It speeds up multi-threaded CPU-bound code"], 1,
     "CPython's GIL serializes bytecode execution across threads, which is why CPU-bound work doesn't parallelize via threading alone."),
    ("What is the difference between `is` and `==` in Python?",
     ["They are always equivalent", "`is` compares object identity, `==` compares value equality",
      "`==` compares identity, `is` compares value", "`is` only works on integers"], 1,
     "`is` checks whether two names refer to the exact same object; `==` checks whether their values are equal."),
    ("What keyword does a Python generator function use to produce values lazily?",
     ["return", "yield", "emit", "send"], 1,
     "`yield` pauses the function and produces a value, resuming from that point on the next call."),
    ("What does `list(zip([1, 2, 3], [4, 5]))` return?",
     ["[(1, 4), (2, 5), (3, None)]", "[(1, 4), (2, 5)]", "[1, 4, 2, 5, 3]", "A ValueError"], 1,
     "`zip` stops at the shortest iterable, so the third element of the first list is dropped."),
    ("Which dictionary method safely retrieves a value without raising KeyError if the key is missing?",
     ["dict[key]", "dict.fetch(key)", "dict.get(key)", "dict.find(key)"], 2,
     "`.get(key)` returns `None` (or a supplied default) instead of raising when the key is absent."),
    ("Python's `with` statement is typically used together with what kind of object?",
     ["A context manager", "A generator only", "A decorator", "A metaclass"], 0,
     "Context managers implement `__enter__`/`__exit__`, which the `with` statement calls to set up and tear down resources."),
    ("What does `functools.lru_cache` do?",
     ["Clears a function's cache automatically on every call",
      "Caches a function's results so repeated calls with the same arguments avoid recomputation",
      "Logs every function call to a file", "Limits the function's recursion depth"], 1,
     "`lru_cache` memoizes results keyed by arguments, evicting least-recently-used entries once a size limit is reached."),
    ("In a try/except/finally block, when does the `finally` block execute?",
     ["Only if no exception occurs", "Only if an exception occurs",
      "Always, regardless of whether an exception occurred", "Never, unless explicitly called"], 2,
     "`finally` is guaranteed to run for cleanup purposes whether or not an exception was raised or caught."),
]

PYTHON_ADVANCED = [
    ("What is the primary purpose of `__slots__` on a Python class?",
     ["To speed up method resolution order", "To restrict instance attributes and reduce per-instance memory overhead",
      "To make a class immutable", "To enable multiple inheritance"], 1,
     "`__slots__` replaces the per-instance `__dict__` with a fixed set of attribute slots, saving memory at scale."),
    ("What does Python's Method Resolution Order (MRO) determine?",
     ["Alphabetical ordering of method names",
      "The order in which base classes are searched when resolving an attribute/method, via C3 linearization",
      "A random order chosen at runtime", "Always strictly left-to-right with no algorithm involved"], 1,
     "Python uses C3 linearization to produce a consistent, cooperative MRO for multiple inheritance."),
    ("What happens when you use a mutable default argument, e.g. `def f(x=[])`?",
     ["A new empty list is created on every call",
      "The same list object persists across calls, which can cause surprising shared-state bugs",
      "Python raises a SyntaxError", "The argument becomes immutable"], 1,
     "Default argument values are evaluated once at function definition time, not on every call."),
    ("For CPU-bound work in CPython, why does `multiprocessing` achieve parallelism that `threading` cannot?",
     ["threading bypasses the GIL for CPU-bound work",
      "multiprocessing uses separate OS processes, each with its own interpreter and GIL, enabling true parallel execution",
      "They are functionally identical for CPU-bound work", "multiprocessing cannot run on Windows"], 1,
     "Separate processes sidestep the single-process GIL entirely, at the cost of inter-process communication overhead."),
    ("What do `async def` and `await` fundamentally provide in Python?",
     ["True OS-level multithreading", "Cooperative concurrency via coroutines scheduled on a single event loop",
      "Automatic parallelization across CPU cores", "Guaranteed faster execution for all I/O"], 1,
     "Async/await enables non-blocking concurrency for I/O-bound work on a single thread, not parallel CPU execution."),
    ("What is a metaclass in Python?",
     ["A class with no methods", "The class of a class -- it controls how classes themselves are constructed",
      "A deprecated Python 2-only feature", "A synonym for an abstract base class"], 1,
     "By default, `type` is the metaclass of all classes; a custom metaclass can customize class creation itself."),
    ("Which statement about CPython's memory management is correct?",
     ["CPython relies solely on generational garbage collection with no reference counting",
      "CPython primarily uses reference counting, supplemented by a generational collector for cyclic references",
      "CPython has no garbage collector; memory must be freed manually",
      "Garbage collection is disabled by default"], 1,
     "Reference counting frees most objects immediately; the cyclic GC exists specifically to catch reference cycles."),
    ("What is the difference between `__new__` and `__init__` in a class?",
     ["They are interchangeable", "`__new__` creates and returns the instance; `__init__` initializes an already-created instance",
      "`__init__` creates the instance; `__new__` initializes it", "Only `__new__` runs for subclasses"], 1,
     "`__new__` is the actual object constructor (rarely overridden); `__init__` sets up state on the object it receives."),
    ("Why can `__slots__`-based classes be faster for attribute access than a regular class?",
     ["They use a fixed, struct-like layout instead of a per-instance `__dict__` lookup",
      "They compile to C automatically", "They disable attribute access entirely", "They cache all method calls globally"], 0,
     "Slot access is a direct offset lookup rather than a dictionary lookup, which is measurably cheaper at scale."),
    ("What is the primary risk of calling `eval()` or `exec()` on untrusted input?",
     ["Slightly slower performance, nothing more", "Arbitrary code execution -- a severe security vulnerability",
      "They are deprecated and will simply raise an error", "They silently fail and return None"], 1,
     "Untrusted input passed to eval/exec can run any Python code with the privileges of the process."),
    ("What does the walrus operator (`:=`), introduced in Python 3.8, allow?",
     ["Assignment as part of a larger expression", "Multiple inheritance", "Type hinting", "Async iteration"], 0,
     "`:=` lets you assign and use a value within the same expression, e.g. `if (n := len(data)) > 10:`."),
    ("Why is `raise NewError(...) from original_error` valuable in production debugging?",
     ["It hides the original traceback for security", "It preserves the causal chain between the original and new exception for diagnostics",
      "It automatically retries the failed operation", "It converts the exception into a warning"], 1,
     "Exception chaining keeps the root cause visible in tracebacks instead of losing it when re-raising a different error type."),
]

FASTAPI_BEGINNER = [
    ("Which HTTP method is typically used to retrieve a resource in a FastAPI endpoint?",
     ["POST", "GET", "DELETE", "PUT"], 1,
     "GET is the conventional, safe/idempotent method for reading a resource."),
    ("How do you define a path parameter in a FastAPI route?",
     ['@app.get("/items/{item_id}")', '@app.get("/items/:item_id")', '@app.get("/items/<item_id>")', '@app.get("/items?item_id")'], 0,
     "FastAPI (via Starlette) uses curly-brace path parameters, matched to a function argument of the same name."),
    ("What library does FastAPI use by default for data validation and serialization?",
     ["marshmallow", "Pydantic", "attrs", "jsonschema"], 1,
     "FastAPI is built around Pydantic models for request/response validation and serialization."),
    ("How does FastAPI know a function parameter is a query parameter rather than a path parameter?",
     ["It's a query parameter automatically if it's a simple-typed function parameter not present in the path",
      "Query parameters must be parsed manually from the raw request", "Only path parameters are supported",
      "You must use a special @query decorator"], 0,
     "Any path-operation function parameter not declared in the path (and not a Pydantic model body) is treated as a query parameter."),
    ("What does FastAPI automatically generate from your route and model definitions?",
     ["Database migrations", "Interactive API documentation (e.g. Swagger UI at /docs)", "Frontend React components", "Docker files"], 1,
     "FastAPI generates an OpenAPI schema and serves interactive docs (Swagger UI / ReDoc) from it automatically."),
    ("Which decorator creates a POST endpoint in FastAPI?",
     ["@app.get", "@app.post", "@app.create", "@app.submit"], 1,
     "`@app.post(...)` registers a path operation that handles HTTP POST requests."),
    ("What is returned by default when a FastAPI endpoint returns a Python dict?",
     ["An HTML page", "A JSON response", "A plain text response", "An XML document"], 1,
     "FastAPI serializes returned Python objects (dicts, Pydantic models) to a JSON response by default."),
    ("What is the standard command to run a FastAPI app in development with auto-reload?",
     ["python app.py --start", "uvicorn main:app --reload", "fastapi run", "npm start"], 1,
     "Uvicorn is the ASGI server that actually runs a FastAPI app; `--reload` restarts it on code changes."),
]

FASTAPI_INTERMEDIATE = [
    ("What is FastAPI's dependency injection system (`Depends`) primarily used for?",
     ["Only for database connections", "Reusable, declarative logic (auth, DB sessions, shared validation) injected into path operations",
      "Styling the generated API docs", "Compiling Python to C"], 1,
     "`Depends` lets you factor out and reuse cross-cutting logic like authentication or database session handling."),
    ("How do you define an async endpoint in FastAPI?",
     ["def endpoint(): with an @async decorator", "async def endpoint():",
      "You cannot define async endpoints in FastAPI", "Using `await` before the route decorator"], 1,
     "Declaring the path operation function with `async def` lets it use `await` for non-blocking I/O."),
    ("What is the purpose of FastAPI/Starlette middleware?",
     ["To validate request bodies only", "To process every request/response globally (logging, CORS, timing) before/after it reaches a path operation",
      "To generate database schemas", "To replace Pydantic models"], 1,
     "Middleware wraps the whole request/response cycle, independent of any specific route."),
    ("How would you enforce that a Pydantic field must be a positive integer?",
     ["Using a plain `int` type only", "Using `Field(gt=0)` or an equivalent constrained type/validator",
      "FastAPI does not support numeric constraints", "By checking manually only after the response is sent"], 1,
     "Pydantic's `Field` supports numeric constraints like `gt`, `ge`, `lt`, `le` enforced at validation time."),
    ("What is a common pattern for authentication in FastAPI?",
     ["Storing credentials in a global variable shared across requests",
      "`OAuth2PasswordBearer` combined with a dependency that decodes/verifies a bearer token",
      "Storing passwords in plaintext in API responses", "Disabling all security checks in development"], 1,
     "FastAPI's security utilities integrate with `Depends` to resolve and verify the current user from a token."),
    ("How does FastAPI typically integrate with a database in an async context?",
     ["It cannot connect to databases", "Via an async driver/ORM (e.g. asyncpg, SQLAlchemy async) with a dependency providing a per-request session",
      "Only synchronous drivers are ever allowed", "By embedding raw SQL directly into the route decorator"], 1,
     "A dependency typically yields a session/connection scoped to the request, then closes it afterward."),
    ("What happens if a Pydantic request model fails validation in FastAPI?",
     ["The server crashes", "FastAPI automatically returns a 422 Unprocessable Entity response with validation details",
      "The request is silently ignored", "It always returns a 500 error"], 1,
     "FastAPI intercepts Pydantic's `ValidationError` and turns it into a structured 422 response automatically."),
    ("What is the benefit of declaring `response_model` on a FastAPI path operation?",
     ["It has no effect on behavior", "It filters/validates the outgoing response shape and improves the generated OpenAPI docs",
      "It only affects request validation", "It disables JSON serialization"], 1,
     "`response_model` both documents and enforces the exact shape of data sent back to clients, hiding extra fields."),
    ("Why might you compose multiple small dependencies with nested `Depends` calls?",
     ["It creates circular imports by design", "To build reusable chains (e.g. get_db -> get_current_user -> require_admin) from smaller pieces",
      "FastAPI does not support nested dependencies", "To bypass Pydantic validation"], 1,
     "Dependencies can themselves depend on other dependencies, letting you compose authorization/data-access logic cleanly."),
    ("What is a common way to test FastAPI endpoints?",
     ["Manual browser testing only", "Using FastAPI's `TestClient` (built on Starlette/httpx) to call the app in-process",
      "FastAPI apps cannot be unit tested", "Only via a live deployment"], 1,
     "`TestClient` runs requests against the ASGI app directly, without a real network call, for fast automated tests."),
]

FASTAPI_ADVANCED = [
    ("Why can blocking (synchronous) code inside an `async def` endpoint hurt throughput?",
     ["It has no effect; Python ignores blocking calls", "It blocks the single event loop thread, stalling every other concurrent request that worker is serving",
      "It automatically spawns a new thread", "FastAPI rejects blocking calls at import time"], 1,
     "An async endpoint that blocks synchronously prevents the event loop from making progress on any other awaiting task."),
    ("What is the recommended way to run CPU-bound or blocking I/O inside an async FastAPI endpoint?",
     ["Call it directly in the async function", "Offload it to a thread pool (e.g. `run_in_threadpool`) or a separate process pool",
      "It's impossible; FastAPI cannot handle blocking code", "Convert the whole app to a synchronous WSGI app"], 1,
     "Delegating blocking work off the event loop thread keeps the loop free to serve other concurrent requests."),
    ("By default, how many times does FastAPI execute a dependency that's used multiple times within the same request?",
     ["It always re-executes the dependency each time it's referenced", "Once -- the result is cached and reused for the rest of that single request",
      "It caches the result globally across all requests forever", "Caching must be manually implemented for every dependency"], 1,
     "FastAPI's default dependency caching is scoped to a single request, avoiding redundant work within it."),
    ("What is a key consideration when scaling a FastAPI app across multiple worker processes?",
     ["In-memory Python state is automatically shared across all workers", "Each worker has independent memory, so shared state needs an external store like Redis rather than in-process globals",
      "FastAPI automatically synchronizes in-memory state across workers", "Horizontal scaling isn't possible with FastAPI"], 1,
     "Multiple worker processes do not share a Python heap, so any cross-request/cross-worker state needs external coordination."),
    ("What is `BackgroundTasks` in FastAPI intended for?",
     ["Running tasks before the request is processed", "Scheduling a lightweight task to run after the response has already been sent to the client",
      "Fully replacing a dedicated task queue like Celery for all workloads", "Running tasks on a separate server automatically"], 1,
     "BackgroundTasks are meant for quick, fire-and-forget work; long-running/critical jobs belong in a real task queue."),
    ("Why is separating routes into multiple `APIRouter` instances considered good practice for larger apps?",
     ["It's required for the app to start", "It allows modular organization, independent prefixes/tags, and easier maintenance as the app grows",
      "It automatically improves runtime performance", "It disables automatic documentation for those routes"], 1,
     "APIRouter lets you group related endpoints into separate modules that are mounted onto the main app."),
    ("What is a risk of using mutable global state (e.g. a module-level dict) as a cache in a multi-worker FastAPI deployment?",
     ["No risk; it behaves identically to a single-process deployment", "Each worker process holds its own independent copy, so cached state can diverge/become inconsistent across workers",
      "FastAPI prevents global state entirely", "It causes a compile-time error"], 1,
     "Without an external shared store, each process's in-memory cache is invisible to the others."),
    ("What is the standard way for a database-session dependency to guarantee cleanup even if the request raises an exception?",
     ["A dependency that returns the session directly with no further code", "A generator-based dependency (using `yield`), where code after the `yield` runs as cleanup similar to a context manager",
      "Cleanup is not possible in FastAPI dependencies", "Manually calling the dependency function again at the end of the request"], 1,
     "Yield-dependencies run their post-yield code in a `finally`-like manner, ensuring resources are released."),
    ("How can validation logic that depends on multiple fields together be implemented in a Pydantic model used by FastAPI?",
     ["It isn't possible in Pydantic", "A model-level validator (e.g. `model_validator` in Pydantic v2) that inspects several fields at once",
      "Only single-field validators exist", "You must validate manually after the response has already been returned"], 1,
     "Model-level validators run after individual field validation and can cross-check relationships between fields."),
    ("Why is FastAPI commonly deployed with Gunicorn managing Uvicorn workers behind a reverse proxy like Nginx?",
     ["FastAPI cannot run without Gunicorn", "To manage multiple worker processes for concurrency/resilience while the proxy handles TLS, static assets, and load balancing",
      "FastAPI requires Nginx to parse JSON", "It's purely a legacy convention with no technical benefit"], 1,
     "This layered setup separates process-management/concurrency concerns from network/TLS/static-asset concerns."),
]

JAVASCRIPT_BEGINNER = [
    ("Which keyword declares a variable that cannot be reassigned in modern JavaScript?",
     ["var", "let", "const", "static"], 2,
     "`const` bindings cannot be reassigned after declaration (though object/array contents can still be mutated)."),
    ('What does `typeof "hello"` return?',
     ['"string"', '"text"', '"char"', '"object"'], 0,
     "String literals have the type `\"string\"` in JavaScript."),
    ("Which array method adds an element to the end of the array?",
     ["array.push()", "array.append()", "array.add()", "array.insert()"], 0,
     "`.push()` appends one or more elements to the end of an array and returns the new length."),
    ("What is the correct way to write a single-line comment in JavaScript?",
     ["# comment", "// comment", "<!-- comment -->", "' comment"], 1,
     "JavaScript uses `//` for single-line comments, similar to C-family languages."),
    ("What does `===` check, compared to `==`, in JavaScript?",
     ["Only value, with type coercion allowed (same as ==)", "Both value AND type, with no type coercion",
      "Only type, ignoring value", "They are identical operators"], 1,
     "`===` (strict equality) requires matching types as well as matching values, avoiding coercion surprises."),
    ("Which function converts a numeric string to an integer in JavaScript?",
     ["Integer.parse()", "parseInt()", "toInt()", "Number.int()"], 1,
     "`parseInt(str)` parses a leading numeric portion of a string into an integer."),
    ("What does `console.log(typeof undefined)` print?",
     ['"null"', '"undefined"', '"object"', '"NaN"'], 1,
     "A variable that has been declared but not assigned a value has the type `\"undefined\"`."),
    ("Which of these correctly defines a function expression in JavaScript?",
     ["function = myFunc() {}", "const myFunc = function() {}", "def myFunc():", "func myFunc() {}"], 1,
     "A function expression assigns an (optionally anonymous) function to a variable."),
]

JAVASCRIPT_INTERMEDIATE = [
    ("What does `this` refer to inside a regular (non-arrow) function called as an object's method?",
     ["The global object, always", "The object the method was called on", "The function itself", "undefined, always"], 1,
     "In method-call syntax (`obj.method()`), `this` is bound to `obj` at call time."),
    ("What is the key difference between arrow functions and regular functions regarding `this`?",
     ["Arrow functions get their own `this` bound at call time", "Arrow functions have no `this` of their own; they inherit it from the enclosing lexical scope",
      "There is no difference", "Regular functions cannot use `this` at all"], 1,
     "Arrow functions capture `this` lexically from where they were defined, not from how they're called."),
    ("What does `Promise.all()` do?",
     ["Runs promises one after another sequentially", "Resolves when ALL promises in the array resolve, or rejects as soon as any one rejects",
      "Cancels all pending promises", "Only works with exactly two promises"], 1,
     "`Promise.all` is used to wait for a set of independent async operations to all complete."),
    ("What is a closure in JavaScript?",
     ["A syntax error", "A function that retains access to variables from its enclosing scope even after that scope has finished executing",
      "A way to close a browser tab", "A deprecated ES5-only feature"], 1,
     "Closures are how inner functions keep working access to outer variables long after the outer function returned."),
    ("What is the purpose of `async`/`await` in JavaScript?",
     ["To run code in a separate OS thread", "To write Promise-based asynchronous code in a more synchronous-looking style",
      "To pause the entire browser tab", "To replace all callbacks with truly synchronous code"], 1,
     "`await` pauses execution of the async function (not the whole program) until the awaited Promise settles."),
    ("What does array destructuring like `const [a, b] = [1, 2]` do?",
     ["Creates a brand-new array", "Unpacks values from an array into separate named variables", "Merges two arrays together", "Throws a syntax error"], 1,
     "Destructuring assigns array elements positionally to the named variables on the left."),
    ("What is event bubbling in the DOM?",
     ["Events only ever fire on the exact element clicked", "An event triggered on a nested element propagates upward through its ancestor elements",
      "Events are queued and never actually fire", "A deprecated jQuery-only feature"], 1,
     "By default, most DOM events bubble from the target element up through its parents, which is why delegation works."),
    ("What does the spread operator do when used on an array, e.g. `[...arr]`?",
     ["Deletes the array", "Expands the array's elements into a new context, such as a new array literal or function arguments",
      "Converts the array to a string", "Reverses the array in place"], 1,
     "Spread is commonly used to shallow-copy or merge arrays/objects without mutating the original."),
    ("What is the difference between `null` and `undefined` in JavaScript?",
     ["They are exactly the same in every situation", "`undefined` means a variable exists but has no assigned value; `null` is an explicit 'no value' assignment",
      "`null` is only used for numbers", "`undefined` is a reserved keyword that can never be used as a value"], 1,
     "`undefined` is JavaScript's own default for unassigned bindings; `null` is a value a programmer assigns intentionally."),
    ("What does `Array.prototype.map()` return?",
     ["A single value", "A new array containing the results of calling a function on every element",
      "The original array mutated in place", "undefined"], 1,
     "`map` is a pure transformation: it never mutates the source array and always returns a new one of the same length."),
]

JAVASCRIPT_ADVANCED = [
    ("What is the JavaScript event loop primarily responsible for?",
     ["Compiling JavaScript to machine code", "Coordinating the call stack, microtask queue, and macrotask queue to enable non-blocking async behavior on a single thread",
      "Managing multiple OS-level threads", "Garbage-collecting DOM nodes"], 1,
     "The event loop is what lets a single-threaded language handle concurrency without blocking on I/O."),
    ("Between microtasks (e.g. Promise callbacks) and macrotasks (e.g. setTimeout), which run first after the current synchronous code finishes?",
     ["Macrotasks always run first", "All pending microtasks run to completion before the next macrotask is processed",
      "They always run strictly in scheduling order regardless of type", "Microtasks never run if a macrotask is queued"], 1,
     "The microtask queue is fully drained between each macrotask, which is a common source of async-ordering surprises."),
    ("What is prototypal inheritance in JavaScript?",
     ["JavaScript does not support inheritance", "Objects can inherit properties/methods directly from other objects via the prototype chain",
      "A TypeScript-only concept", "A synonym for the ES6 `class` keyword"], 1,
     "`class` in JavaScript is syntactic sugar over the same underlying prototype-chain mechanism."),
    ("What problem does `WeakMap` solve compared to a regular `Map` when objects are used as keys?",
     ["WeakMap is simply faster in every case", "WeakMap holds weak references to its keys, letting them be garbage-collected when no longer referenced elsewhere, avoiding memory leaks",
      "WeakMap allows primitive values as keys, unlike Map", "WeakMap is asynchronous while Map is synchronous"], 1,
     "Because WeakMap doesn't prevent garbage collection of its keys, it's well-suited to per-object metadata caches."),
    ("What is a common cause of memory leaks in long-running JavaScript apps (e.g. single-page apps)?",
     ["Using `const` instead of `let`", "Forgotten event listeners or timers that keep references to DOM nodes/closures alive indefinitely",
      "Using arrow functions", "Declaring too many local variables"], 1,
     "Un-removed listeners/timers are a classic source of leaks since they keep otherwise-unreachable objects reachable."),
    ("What does `Object.freeze()` do?",
     ["Deep-freezes an object and all nested objects automatically", "Prevents adding, removing, or reassigning properties at the object's top level only (shallow)",
      "Converts the object to a JSON string", "Pauses every method on the object"], 1,
     "Freeze is shallow: nested objects referenced by a frozen object's properties are not themselves frozen."),
    ("Why can `JSON.parse(JSON.stringify(obj))` be a problematic way to deep-clone an object?",
     ["It is always the fastest possible way to deep clone", "It silently drops functions, undefined, and Symbols, and turns Dates into strings, which can be lossy for complex objects",
      "It only works on arrays", "It mutates the original object"], 1,
     "This trick round-trips through JSON, which has a much narrower type system than JavaScript itself."),
    ("What is 'debouncing' typically used for in front-end performance work?",
     ["Permanently disabling an event handler", "Delaying a function's execution until a burst of calls has stopped, to avoid excessive invocations (e.g. on resize/input)",
      "Running a function immediately on every event, unmodified", "Converting synchronous code into asynchronous code"], 1,
     "Debouncing coalesces rapid-fire events (typing, resizing) into a single trailing call."),
    ("What does `Object.defineProperty()` allow that plain assignment does not?",
     ["Nothing; they behave identically", "Fine-grained control over a property's writable/enumerable/configurable flags and getter/setter behavior",
      "It can only be used on arrays", "It automatically makes a property asynchronous"], 1,
     "defineProperty exposes the full property descriptor API, enabling things like read-only or computed properties."),
    ("In engines like V8, what does the 'hidden classes' (shapes) optimization relate to?",
     ["Hiding CSS classes from the DOM", "An internal engine optimization that tracks consistent object structure to speed up property access",
      "A deprecated jQuery feature", "A security feature unrelated to performance"], 1,
     "Objects that consistently have the same shape let the engine generate much faster property-access code."),
    ("What is the difference between `Object.keys()`, `Object.values()`, and `Object.entries()`?",
     ["They all return the exact same result", "They return an object's own enumerable property keys, values, or [key, value] pairs respectively",
      "They only work on arrays", "They mutate the original object"], 1,
     "These three methods provide the three natural views over an object's own enumerable properties."),
    ("Why does the difference between shallow copy and deep copy matter in state management (e.g. React/Redux)?",
     ["It has no practical impact", "Mutating nested state reached via a shallow copy shares references with the original, breaking reference-equality checks used for re-renders",
      "JavaScript automatically deep-copies everything by default", "Shallow and deep copies always produce identical results"], 1,
     "Frameworks that rely on `===` reference checks to detect changes need genuinely new references at every level that changed."),
]

CPP_BEGINNER = [
    ("Which header is required to use `std::cout` in C++?",
     ["<iostream>", "<stdio.h>", "<string>", "<cstdlib>"], 0,
     "`std::cout` and `std::cin` are declared in the `<iostream>` header."),
    ("What is the correct way to declare an integer variable named `x` in C++?",
     ["int x;", "var x;", "x: int;", "integer x;"], 0,
     "C++ uses `type name;` declaration syntax, e.g. `int x;`."),
    ("Which operator accesses a member of an object through a pointer in C++?",
     [".", "->", "::", "&"], 1,
     "`->` dereferences a pointer and accesses a member in one operation; `.` is used on the object directly."),
    ("What does `sizeof(int)` typically return on most common modern platforms?",
     ["2", "4", "8", "It's undefined with no common value in practice"], 1,
     "On the vast majority of modern desktop/server platforms, `int` is 4 bytes, though the standard doesn't guarantee an exact size."),
    ("Which keyword defines a compile-time constant in C++?",
     ["final", "const", "static", "readonly"], 1,
     "`const` marks a variable as not modifiable after initialization."),
    ("What is the correct syntax for a for loop that runs 5 times in C++?",
     ["for (int i = 0; i < 5; i++)", "for i in range(5)", "for (i = 0 to 5)", "loop(5)"], 0,
     "C++'s classic for loop has init; condition; increment clauses separated by semicolons."),
    ("Which of these correctly declares a function that returns nothing?",
     ["void myFunction()", "null myFunction()", "empty myFunction()", "none myFunction()"], 0,
     "`void` is the return type used for functions that do not return a value."),
    ("What is the purpose of the `#include` directive?",
     ["To define a new class", "To include the contents of another file (like a header) into the current source file before compilation",
      "To start the main function", "To comment out code"], 1,
     "`#include` is a preprocessor directive that textually inserts a header file's contents."),
]

CPP_INTERMEDIATE = [
    ("What is the main difference between a `struct` and a `class` in C++?",
     ["struct cannot have member functions", "By default, struct members are public and class members are private; otherwise they are largely equivalent",
      "class cannot use inheritance", "struct is deprecated in modern C++"], 1,
     "Aside from the default access specifier, struct and class are essentially the same construct in C++."),
    ("What does RAII (Resource Acquisition Is Initialization) mean in C++?",
     ["A naming convention with no functional effect", "Tying a resource's lifetime (memory, file handles, locks) to an object's lifetime, so it's released automatically when that object goes out of scope",
      "A macro used for random number generation", "A multithreading library"], 1,
     "RAII is the foundation of safe, exception-resilient resource management in idiomatic C++."),
    ("What is the purpose of a virtual function in C++?",
     ["To prevent a function from ever being overridden", "To enable runtime polymorphism, so a derived class's override is called through a base class pointer/reference",
      "To make a function execute faster", "To make a function static"], 1,
     "Virtual functions are resolved via the vtable at runtime based on the object's actual dynamic type."),
    ("What does `std::vector` provide over a raw C-style array?",
     ["They are identical in every respect", "Dynamic resizing at runtime plus safety/convenience features like bounds-checked `.at()` access",
      "Raw arrays are always faster and safer", "std::vector cannot store primitive types"], 1,
     "std::vector manages its own heap-allocated buffer and grows automatically as elements are added."),
    ("What does a smart pointer like `std::unique_ptr` provide over a raw pointer?",
     ["Faster pointer arithmetic", "Automatic memory management via RAII, with exclusive (non-shared) ownership of the pointed-to object",
      "Free sharing of ownership across many pointers", "Compatibility only with C-style malloc/free"], 1,
     "unique_ptr deletes its managed object automatically when it goes out of scope, and cannot be copied (only moved)."),
    ("What is operator overloading in C++?",
     ["Using too many operators in a single expression", "Defining custom behavior for existing operators (like `+` or `==`) when applied to user-defined types",
      "A compiler error condition", "A feature usable only with built-in types"], 1,
     "Operator overloading lets user-defined types participate naturally in expressions, e.g. adding two custom Vector objects."),
    ("What is the purpose of marking a member function `const` in C++?",
     ["It has no real effect and is purely stylistic", "It signals, and the compiler enforces, that the function does not modify the object's state, allowing it to be called on const objects",
      "It makes the function run on a separate thread", "It disables the function entirely"], 1,
     "const-correctness lets the compiler catch accidental state mutations and enables use on const references."),
    ("What does the Standard Template Library (STL) provide?",
     ["Only I/O functions", "Generic reusable containers (vector, map, set, etc.), iterators, and algorithms",
      "A garbage collector", "A replacement for the C++ compiler"], 1,
     "The STL is the standard collection of generic, reusable data structures and algorithms in C++."),
    ("What mechanism does C++ use for exception handling?",
     ["if/else statements only", "try, catch, and throw blocks", "goto statements", "C++ has no exception handling"], 1,
     "C++ uses try/catch/throw, with RAII destructors running automatically during stack unwinding."),
    ("What is function overloading in C++?",
     ["Calling a function too many times", "Defining multiple functions with the same name but different parameter lists, resolved at compile time",
      "Recursively calling a function", "A runtime-only mechanism with no compile-time resolution"], 1,
     "The compiler selects the correct overload based on the argument types/count at the call site."),
]

CPP_ADVANCED = [
    ("What is the 'Rule of Three/Five' in modern C++?",
     ["A style guideline about naming functions", "If a class defines any of destructor/copy-constructor/copy-assignment (and, in C++11+, move-constructor/move-assignment), it likely needs to define all of them",
      "A rule limiting a class to 3-5 member variables", "A deprecated C++98-only concept"], 1,
     "These special member functions are closely related for resource-owning classes; defining one usually implies needing the others."),
    ("What is the primary purpose of `std::move` in C++11 and later?",
     ["It physically relocates memory to a new address", "It casts an lvalue to an rvalue reference, enabling move semantics (transferring ownership instead of copying)",
      "It deletes the original object immediately", "It only works with primitive types"], 1,
     "std::move doesn't move anything itself -- it's a cast that makes an object eligible for move construction/assignment."),
    ("What is undefined behavior (UB) in C++, and why is it dangerous?",
     ["A compiler warning with no runtime effect", "Behavior the standard places no requirements on (e.g. buffer overrun, null dereference); the program may appear to work until it doesn't",
      "A synonym for a caught runtime exception", "A concept relevant only to multithreaded code"], 1,
     "UB means the compiler is free to assume it never happens, which can produce surprising, non-local miscompilations."),
    ("What risk does a `virtual` base class combined with a non-virtual destructor create?",
     ["No risk; destructors always run correctly regardless", "Deleting a derived object through a base pointer with a non-virtual base destructor causes undefined behavior, typically leaking derived-class resources",
      "It always causes a compile-time error", "It only matters for structs, not classes"], 1,
     "Polymorphic base classes intended for deletion through a base pointer need a virtual destructor."),
    ("What is template metaprogramming used for in C++?",
     ["Runtime-only code generation", "Performing computation and code generation at COMPILE time, enabling generic, type-safe, sometimes zero-overhead abstractions",
      "A deprecated feature removed in C++20", "Exclusively for GUI frameworks"], 1,
     "Templates let the compiler generate specialized code per type, often with no runtime cost over hand-written code."),
    ("What is a data race in C++ multithreading?",
     ["A benign performance issue with no correctness impact", "Undefined behavior from two threads accessing the same memory concurrently, with at least one write, without synchronization",
      "A synonym for deadlock", "Something only possible when using std::mutex"], 1,
     "The C++ standard defines concurrent unsynchronized access with a write as UB, not just 'unpredictable output'."),
    ("What is `std::atomic` used for in concurrent C++ programming?",
     ["Making an entire program single-threaded", "Providing indivisible operations on shared variables without requiring a full mutex, useful for lock-free/low-level synchronization",
      "Automatically parallelizing loops", "Replacing all mutexes with identical behavior"], 1,
     "Atomics give well-defined, lock-free semantics for simple shared counters/flags across threads."),
    ("Why can returning a reference to a local (stack) variable cause undefined behavior?",
     ["It doesn't; references outlive function scope indefinitely", "The local variable's storage is destroyed when the function returns, leaving the reference dangling",
      "C++ automatically promotes local variables to the heap in this case", "It only matters for pointers, not references"], 1,
     "Once the function returns, the stack frame (and the variable within it) no longer exists."),
    ("Why do move semantics benefit operations like returning a large `std::vector` from a function?",
     ["They don't; copies and moves cost the same", "They avoid an expensive deep copy by transferring the internal buffer pointer from source to destination",
      "Moves always allocate new memory just like copies", "Move semantics only apply to primitive types"], 1,
     "A move typically just swaps a few internal pointers/sizes instead of copying every element."),
    ("What is a key pitfall of `reinterpret_cast`?",
     ["It is always perfectly safe and portable", "It reinterprets an object's bits as an often-unrelated type, which can violate strict aliasing rules and cause undefined behavior",
      "It performs the same runtime safety checks as dynamic_cast", "It cannot be used with pointers"], 1,
     "reinterpret_cast performs no safety checks at all -- it's the most dangerous of the C++ cast operators."),
    ("Why does cache locality matter in performance-critical C++ code?",
     ["It's better to prioritize pointer-heavy linked structures for all data", "Structuring data contiguously (e.g. std::vector) maximizes CPU cache hits, since memory access patterns heavily affect real-world performance",
      "It's a reason to avoid the STL entirely", "It means recursion is always preferable to iteration"], 1,
     "Contiguous memory access patterns are dramatically faster than scattered ones due to CPU cache behavior."),
    ("Why is `dynamic_cast` generally safer, but potentially slower, than `static_cast` for downcasting in a polymorphic hierarchy?",
     ["They are functionally identical in every case", "dynamic_cast performs a runtime type check (via RTTI) and fails safely (nullptr/exception); static_cast performs no such check and is unsafe if the type is wrong",
      "static_cast is slower because it performs more checks", "dynamic_cast cannot be used with pointers"], 1,
     "dynamic_cast trades a small runtime cost for safety when the actual derived type isn't known at compile time."),
]

SKILLS = {
    "Python": {
        "Beginner": {"duration_minutes": 10, "select_count": 5, "passing_percentage": 60, "questions": PYTHON_BEGINNER},
        "Intermediate": {"duration_minutes": 15, "select_count": 6, "passing_percentage": 65, "questions": PYTHON_INTERMEDIATE},
        "Advanced": {"duration_minutes": 20, "select_count": 7, "passing_percentage": 70, "questions": PYTHON_ADVANCED},
    },
    "FastAPI": {
        "Beginner": {"duration_minutes": 10, "select_count": 5, "passing_percentage": 60, "questions": FASTAPI_BEGINNER},
        "Intermediate": {"duration_minutes": 15, "select_count": 6, "passing_percentage": 65, "questions": FASTAPI_INTERMEDIATE},
        "Advanced": {"duration_minutes": 20, "select_count": 7, "passing_percentage": 70, "questions": FASTAPI_ADVANCED},
    },
    "JavaScript": {
        "Beginner": {"duration_minutes": 10, "select_count": 5, "passing_percentage": 60, "questions": JAVASCRIPT_BEGINNER},
        "Intermediate": {"duration_minutes": 15, "select_count": 6, "passing_percentage": 65, "questions": JAVASCRIPT_INTERMEDIATE},
        "Advanced": {"duration_minutes": 20, "select_count": 7, "passing_percentage": 70, "questions": JAVASCRIPT_ADVANCED},
    },
    "C++": {
        "Beginner": {"duration_minutes": 10, "select_count": 5, "passing_percentage": 60, "questions": CPP_BEGINNER},
        "Intermediate": {"duration_minutes": 15, "select_count": 6, "passing_percentage": 65, "questions": CPP_INTERMEDIATE},
        "Advanced": {"duration_minutes": 20, "select_count": 7, "passing_percentage": 70, "questions": CPP_ADVANCED},
    },
}
