-- AIC Portal — Initial Skill Catalog Seed
-- Corrected/restructured version.
-- Populates ONLY public.skill_categories and public.skills.
-- Safe to run repeatedly; no student-owned data is seeded.

begin;

-- 1) Categories
insert into public.skill_categories (name)
values
  ('Programming Languages'),
  ('Web Development'),
  ('Frontend Frameworks'),
  ('Backend Frameworks'),
  ('Databases'),
  ('Cloud Computing'),
  ('DevOps'),
  ('Tools & Version Control'),
  ('Data Science'),
  ('Artificial Intelligence'),
  ('Machine Learning'),
  ('Deep Learning'),
  ('Generative AI'),
  ('Cybersecurity'),
  ('Mobile Development'),
  ('UI/UX & Design'),
  ('Testing & QA'),
  ('Data Engineering'),
  ('Big Data'),
  ('Soft Skills'),
  ('Business & Management')
on conflict do nothing;

-- 2) Skills
-- Category names are data values, never SQL identifiers.
with seed_skills (name, category_name, description) as (
  values
  ('Python', 'Programming Languages', 'General-purpose language widely used in web, data, and AI.'),
  ('Java', 'Programming Languages', 'Object-oriented language widely used in enterprise and Android apps.'),
  ('JavaScript', 'Programming Languages', 'Core scripting language for interactive web applications.'),
  ('TypeScript', 'Programming Languages', 'Typed superset of JavaScript for safer, scalable code.'),
  ('C', 'Programming Languages', 'Low-level systems programming language.'),
  ('C++', 'Programming Languages', 'Performance-oriented language used in systems and game development.'),
  ('C#', 'Programming Languages', 'Object-oriented language used with .NET and game development.'),
  ('Go', 'Programming Languages', 'Compiled language known for concurrency and cloud-native services.'),
  ('Rust', 'Programming Languages', 'Systems language focused on memory safety and performance.'),
  ('PHP', 'Programming Languages', 'Server-side scripting language widely used for web backends.'),
  ('Ruby', 'Programming Languages', 'Dynamic language known for developer productivity and Rails.'),
  ('Kotlin', 'Programming Languages', 'Modern language for Android and JVM development.'),
  ('Swift', 'Programming Languages', 'Apple''s language for iOS and macOS development.'),
  ('Dart', 'Programming Languages', 'Language used to build cross-platform apps with Flutter.'),
  ('SQL', 'Programming Languages', 'Standard language for querying and managing relational data.'),
  ('HTML', 'Web Development', 'Markup language for structuring web content.'),
  ('CSS', 'Web Development', 'Stylesheet language for designing and laying out web pages.'),
  ('Tailwind CSS', 'Web Development', 'Utility-first CSS framework for rapid UI styling.'),
  ('React', 'Frontend Frameworks', 'Component-based JavaScript library for building user interfaces.'),
  ('Next.js', 'Frontend Frameworks', 'React framework for server-rendered and static web apps.'),
  ('Angular', 'Frontend Frameworks', 'TypeScript-based framework for building large-scale web apps.'),
  ('Vue.js', 'Frontend Frameworks', 'Progressive JavaScript framework for building user interfaces.'),
  ('Svelte', 'Frontend Frameworks', 'Compiler-based framework for building fast web interfaces.'),
  ('Node.js', 'Backend Frameworks', 'JavaScript runtime for building server-side applications.'),
  ('Express.js', 'Backend Frameworks', 'Minimal web framework for Node.js backends.'),
  ('FastAPI', 'Backend Frameworks', 'Modern Python framework for building fast APIs.'),
  ('Django', 'Backend Frameworks', 'High-level Python framework for rapid web development.'),
  ('Flask', 'Backend Frameworks', 'Lightweight Python framework for web applications and APIs.'),
  ('Spring Boot', 'Backend Frameworks', 'Java framework for building production-ready applications.'),
  ('.NET', 'Backend Frameworks', 'Microsoft framework for building cross-platform applications.'),
  ('PostgreSQL', 'Databases', 'Advanced open-source relational database.'),
  ('MySQL', 'Databases', 'Widely used open-source relational database.'),
  ('SQLite', 'Databases', 'Lightweight, file-based relational database.'),
  ('MongoDB', 'Databases', 'Document-oriented NoSQL database.'),
  ('Redis', 'Databases', 'In-memory data store used for caching and queues.'),
  ('Firebase', 'Databases', 'Backend-as-a-service platform with a real-time NoSQL database.'),
  ('AWS', 'Cloud Computing', 'Amazon''s cloud computing platform and services.'),
  ('Microsoft Azure', 'Cloud Computing', 'Microsoft''s cloud computing platform and services.'),
  ('Google Cloud Platform', 'Cloud Computing', 'Google''s cloud computing platform and services.'),
  ('Docker', 'DevOps', 'Platform for building and running containerized applications.'),
  ('Kubernetes', 'DevOps', 'Container orchestration platform for deploying at scale.'),
  ('GitHub Actions', 'DevOps', 'CI/CD automation built into GitHub.'),
  ('Jenkins', 'DevOps', 'Open-source automation server for CI/CD pipelines.'),
  ('Terraform', 'DevOps', 'Infrastructure-as-code tool for provisioning cloud resources.'),
  ('CI/CD', 'DevOps', 'Practice of automating build, test, and deployment pipelines.'),
  ('Git', 'Tools & Version Control', 'Distributed version control system for tracking code changes.'),
  ('GitHub', 'Tools & Version Control', 'Platform for hosting and collaborating on Git repositories.'),
  ('GitLab', 'Tools & Version Control', 'Platform for Git repository hosting and DevOps pipelines.'),
  ('Postman', 'Tools & Version Control', 'Tool for building, testing, and documenting APIs.'),
  ('Linux', 'Tools & Version Control', 'Open-source operating system widely used in servers and DevOps.'),
  ('VS Code', 'Tools & Version Control', 'Popular lightweight source code editor.'),
  ('Data Analysis', 'Data Science', 'Examining data to extract insights and inform decisions.'),
  ('Pandas', 'Data Science', 'Python library for data manipulation and analysis.'),
  ('NumPy', 'Data Science', 'Python library for numerical and array computing.'),
  ('Matplotlib', 'Data Science', 'Python library for data visualization.'),
  ('Power BI', 'Data Science', 'Microsoft''s business analytics and visualization tool.'),
  ('Tableau', 'Data Science', 'Data visualization and business intelligence tool.'),
  ('Artificial Intelligence', 'Artificial Intelligence', 'Building systems that perform tasks requiring human-like intelligence.'),
  ('Natural Language Processing', 'Artificial Intelligence', 'Enabling computers to understand and generate human language.'),
  ('Computer Vision', 'Artificial Intelligence', 'Enabling computers to interpret and process visual data.'),
  ('Machine Learning', 'Machine Learning', 'Building models that learn patterns from data.'),
  ('Scikit-learn', 'Machine Learning', 'Python library for classical machine learning.'),
  ('Deep Learning', 'Deep Learning', 'Building and training neural networks on large datasets.'),
  ('PyTorch', 'Deep Learning', 'Deep learning framework popular for research and production.'),
  ('TensorFlow', 'Deep Learning', 'Deep learning framework for building and deploying models.'),
  ('Generative AI', 'Generative AI', 'Building systems that generate text, images, or other content.'),
  ('Large Language Models', 'Generative AI', 'Working with and applying large-scale language models.'),
  ('Prompt Engineering', 'Generative AI', 'Designing effective prompts to guide AI model outputs.'),
  ('Hugging Face', 'Generative AI', 'Platform and libraries for sharing and using AI models.'),
  ('Network Security', 'Cybersecurity', 'Protecting network infrastructure from threats and attacks.'),
  ('Web Security', 'Cybersecurity', 'Securing web applications against common vulnerabilities.'),
  ('Application Security', 'Cybersecurity', 'Building and testing software to resist attacks.'),
  ('Ethical Hacking', 'Cybersecurity', 'Legally testing systems to find security weaknesses.'),
  ('Penetration Testing', 'Cybersecurity', 'Simulating attacks to evaluate system security.'),
  ('OWASP', 'Cybersecurity', 'Following best practices for secure application development.'),
  ('Cryptography', 'Cybersecurity', 'Techniques for securing data through encryption.'),
  ('Security Operations', 'Cybersecurity', 'Monitoring and responding to security incidents.'),
  ('Android Development', 'Mobile Development', 'Building native applications for the Android platform.'),
  ('iOS Development', 'Mobile Development', 'Building native applications for the iOS platform.'),
  ('React Native', 'Mobile Development', 'Framework for building cross-platform mobile apps with React.'),
  ('Flutter', 'Mobile Development', 'Google''s toolkit for building cross-platform apps with Dart.'),
  ('UI Design', 'UI/UX & Design', 'Designing visual interfaces for digital products.'),
  ('UX Design', 'UI/UX & Design', 'Designing user experiences based on usability and research.'),
  ('Figma', 'UI/UX & Design', 'Collaborative interface design and prototyping tool.'),
  ('Wireframing', 'UI/UX & Design', 'Creating low-fidelity layouts to plan interfaces.'),
  ('Prototyping', 'UI/UX & Design', 'Building interactive mockups to test design concepts.'),
  ('User Research', 'UI/UX & Design', 'Studying user needs and behavior to inform design.'),
  ('Software Testing', 'Testing & QA', 'Verifying that software behaves as expected.'),
  ('Unit Testing', 'Testing & QA', 'Testing individual components of code in isolation.'),
  ('Integration Testing', 'Testing & QA', 'Testing how combined components work together.'),
  ('API Testing', 'Testing & QA', 'Verifying the functionality and reliability of APIs.'),
  ('Automation Testing', 'Testing & QA', 'Using tools to automatically run test cases.'),
  ('Selenium', 'Testing & QA', 'Tool for automating web browser testing.'),
  ('Playwright', 'Testing & QA', 'Modern tool for automated end-to-end web testing.'),
  ('Cypress', 'Testing & QA', 'JavaScript-based tool for end-to-end web testing.'),
  ('ETL', 'Data Engineering', 'Extracting, transforming, and loading data between systems.'),
  ('Data Warehousing', 'Data Engineering', 'Designing systems to store and analyze large datasets.'),
  ('Apache Spark', 'Big Data', 'Distributed engine for large-scale data processing.'),
  ('Hadoop', 'Big Data', 'Framework for distributed storage and processing of big data.'),
  ('Communication', 'Soft Skills', 'Clearly conveying ideas and information to others.'),
  ('Leadership', 'Soft Skills', 'Guiding and motivating individuals or teams toward goals.'),
  ('Teamwork', 'Soft Skills', 'Collaborating effectively with others to achieve shared goals.'),
  ('Problem Solving', 'Soft Skills', 'Identifying issues and developing effective solutions.'),
  ('Critical Thinking', 'Soft Skills', 'Analyzing information objectively to make sound judgments.'),
  ('Time Management', 'Soft Skills', 'Organizing and prioritizing tasks to use time effectively.'),
  ('Adaptability', 'Soft Skills', 'Adjusting effectively to new conditions and challenges.'),
  ('Public Speaking', 'Soft Skills', 'Communicating confidently and clearly to an audience.'),
  ('Collaboration', 'Soft Skills', 'Working with others to achieve a common goal.'),
  ('Project Management', 'Business & Management', 'Planning and overseeing projects to meet goals.'),
  ('Product Management', 'Business & Management', 'Guiding product strategy and development.'),
  ('Business Analysis', 'Business & Management', 'Identifying business needs and recommending solutions.'),
  ('Entrepreneurship', 'Business & Management', 'Identifying opportunities and building new ventures.'),
  ('Agile', 'Business & Management', 'Iterative approach to managing and delivering projects.'),
  ('Scrum', 'Business & Management', 'Framework for managing work using an Agile approach.')
)
insert into public.skills (name, category_id, description, is_active)
select s.name, c.id, s.description, true
from seed_skills as s
join public.skill_categories as c
  on lower(c.name) = lower(s.category_name)
on conflict do nothing;

commit;

-- Expected seed: 21 categories, 114 skills.